FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install poetry

WORKDIR /migrations

COPY poetry.lock pyproject.toml /
RUN poetry config virtualenvs.create false && \
    poetry install --without dev --no-interaction --no-ansi --no-root

COPY alembic.ini .
COPY alembic/ ./alembic/
COPY src/config.py ./src/config.py
COPY src/domain/models/ ./src/domain/models/

CMD ["alembic", "upgrade", "head"]