"""add habit_dates

Revision ID: 5afb56da91f8
Revises: a9acf3d870f9
Create Date: 2026-02-14 17:08:09.875081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import advanced_alchemy


# revision identifiers, used by Alembic.
revision: str = '5afb56da91f8'
down_revision: Union[str, None] = 'a9acf3d870f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_dates',
    sa.Column('completed_at', sa.Date(), nullable=False),
    sa.Column('habit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.username'], name=op.f('fk_habit_dates_author_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], name=op.f('fk_habit_dates_habit_id_habits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habit_dates')),
    sa.UniqueConstraint('habit_id', 'author', 'completed_at', name='uq_habit_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit_dates')
    # ### end Alembic commands ###
