"""update habits

Revision ID: a9acf3d870f9
Revises: e8ab00c77e4a
Create Date: 2026-02-07 00:28:33.030911

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9acf3d870f9"
down_revision: Union[str, None] = "e8ab00c77e4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("habits", sa.Column("count", sa.Integer(), nullable=False))
    op.add_column("habits", sa.Column("period", sa.String(), nullable=False))
    op.add_column("habits", sa.Column("period_in_days", sa.Integer(), nullable=False))
    op.alter_column(
        "habits",
        "current_streak_start_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.Date(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "habits",
        "current_streak_start_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.drop_column("habits", "period_in_days")
    op.drop_column("habits", "period")
    op.drop_column("habits", "count")
    # ### end Alembic commands ###
