"""Initial schema

Revision ID: e8ab00c77e4a
Revises:
Create Date: 2026-01-31 23:18:54.578997

"""

from typing import Sequence, Union

import sqlalchemy as sa
from advanced_alchemy.types.datetime import DateTimeUTC

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8ab00c77e4a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("created_at", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "habits",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("current_streak_start_date", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("current_streak_days", sa.Integer(), nullable=False),
        sa.Column("max_streak_days", sa.Integer(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("created_at", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author"], ["users.username"], name=op.f("fk_habits_author_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_habits")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("habits")
    op.drop_table("users")
    # ### end Alembic commands ###
