"""add habit_dates

Revision ID: ef391b9017fd
Revises: a9acf3d870f9
Create Date: 2026-02-07 13:27:39.648489

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ef391b9017fd'
down_revision: Union[str, None] = 'a9acf3d870f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_dates',
    sa.Column('completed_at', sa.Date(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['title'], ['habits.title'], name=op.f('fk_habit_dates_title_habits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('completed_at', 'title', name=op.f('pk_habit_dates'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit_dates')
    # ### end Alembic commands ###
